#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: "639330016853-7ma2jo5165s7eoe09gg971jotvqvt1q3.apps.googleusercontent.com"
#            client-secret: "zBxwZe10pxeYPEsQtMD66fSt"
#            scope: profile,email
#          naver:
#            client-id: "bThWPeK1YZqJKjV3YXil"
#            client-secret: "Yhh3rmvpa_"
#            redirect-url: http://localhost/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            scope: email
#            client-email: Naver
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            token-uri: https://nid.naver.com/v1/nid/token
#            user-name-attribute: response